---

name: Pull Request (main)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - main

jobs:
  check_package_version:
    name: Check Package Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: chmod +x .github/check-package-version
      - run: .github/check-package-version
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: check_package_version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: rm -rf node_modules
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
