jobs:
  check_package_version:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Check Package Version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'

      - run: rm -rf node_modules

      - run: npm install --global yarn

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn test

      - uses: dudo/tag_check@v1.0.0
        with:
          git_tag_prefix: v

    runs-on: ubuntu-latest

name: Create Pull Request

on:
  pull_request:
    branches:
      - main
