name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 'main' Branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install CI
        run: rm -rf node_modules
        run: yarn install --frozen-lockfile
      - name: Run Build
        run: yarn build
      - name: Run Tests
        run: yarn test
      - name: Release NPM Package
        run: yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
